module.exports = `<?xml version="1.0" encoding="UTF-8"?>
<myanimelist>
    <myinfo>
        <user_export_type>1</user_export_type>
    </myinfo>
    <anime>
        <series_title>Steins;Gate</series_title>
        <series_type>tv</series_type>
        <series_episodes>24</series_episodes>
        <series_animedb_id>9253</series_animedb_id>
        <my_watched_episodes>24</my_watched_episodes>
        <my_times_watched>0</my_times_watched>
        <my_score>9</my_score>
        <my_status>Completed</my_status>
        <shiki_status>Completed</shiki_status>
        <my_comments/>
        <update_on_import>1</update_on_import>
    </anime>
    <anime>
        <series_title>Fullmetal Alchemist: Brotherhood</series_title>
        <series_type>tv</series_type>
        <series_episodes>64</series_episodes>
        <series_animedb_id>5114</series_animedb_id>
        <my_watched_episodes>64</my_watched_episodes>
        <my_times_watched>0</my_times_watched>
        <my_score>10</my_score>
        <my_status>Completed</my_status>
        <shiki_status>Completed</shiki_status>
        <my_comments/>
        <update_on_import>1</update_on_import>
    </anime>
    <anime>
        <series_title>Code Geass: Hangyaku no Lelouch R2</series_title>
        <series_type>tv</series_type>
        <series_episodes>25</series_episodes>
        <series_animedb_id>2904</series_animedb_id>
        <my_watched_episodes>25</my_watched_episodes>
        <my_times_watched>0</my_times_watched>
        <my_score>8</my_score>
        <my_status>Completed</my_status>
        <shiki_status>Completed</shiki_status>
        <my_comments/>
        <update_on_import>1</update_on_import>
    </anime>
</myanimelist>
`;
