module.exports = [
  {
    'id': 15016,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/record_image600_white_fill.png',
    'title': 'Record',
    'url': 'https://radiorecord.hostingradio.ru/rr_main96.aacp',
  },
  {
    'id': 43696,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/tiesto_image600_white_fill.png',
    'title': 'Tiesto',
    'url': 'https://radiorecord.hostingradio.ru/tiesto96.aacp',
  },
  {
    'id': 43695,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/guetta_image600_white_fill.png',
    'title': 'David Guetta',
    'url': 'https://radiorecord.hostingradio.ru/guetta96.aacp',
  },
  {
    'id': 43697,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/armin_image600_white_fill.png',
    'title': 'Armin van Buuren',
    'url': 'https://radiorecord.hostingradio.ru/armin96.aacp',
  },
  {
    'id': 539,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/sd90_image600_white_fill.png',
    'title': 'Супердискотека 90-х',
    'url': 'https://radiorecord.hostingradio.ru/sd9096.aacp',
  },
  {
    'id': 43601,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/ruszima_image600_white_fill.png',
    'title': 'Русская Зима',
    'url': 'https://radiorecord.hostingradio.ru/ruszima96.aacp',
  },
  {
    'id': 537,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/rus_image600_white_fill.png',
    'title': 'Russian Mix',
    'url': 'https://radiorecord.hostingradio.ru/rus96.aacp',
  },
  {
    'id': 519,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/russianhits_image600_white_fill.png',
    'title': 'Russian Hits',
    'url': 'https://radiorecord.hostingradio.ru/russianhits96.aacp',
  },
  {
    'id': 534,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/chil_image600_white_fill.png',
    'title': 'Chill-Out',
    'url': 'https://radiorecord.hostingradio.ru/chil96.aacp',
  },
  {
    'id': 42375,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/christmas-radio_image600_white_fill.png',
    'title': 'Christmas',
    'url': 'https://radiorecord.hostingradio.ru/christmas96.aacp',
  },
  {
    'id': 528,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/deep_image600_white_fill.png',
    'title': 'Deep',
    'url': 'https://radiorecord.hostingradio.ru/deep96.aacp',
  },
  {
    'id': 43069,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/christmas-chill_image600_white_fill.png',
    'title': 'Christmas Chill',
    'url': 'https://radiorecord.hostingradio.ru/christmaschill96.aacp',
  },
  {
    'id': 536,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/ps_image600_white_fill.png',
    'title': 'Pirate Station',
    'url': 'https://radiorecord.hostingradio.ru/ps96.aacp',
  },
  {
    'id': 42891,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/party-24-7_image600_white_fill.png',
    'title': 'Party 24/7',
    'url': 'https://radiorecord.hostingradio.ru/party96.aacp',
  },
  {
    'id': 495,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/mf_image600_white_fill.png',
    'title': 'Маятник Фуко',
    'url': 'https://radiorecord.hostingradio.ru/mf96.aacp',
  },
  {
    'id': 43264,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/record00_image600_white_fill.png',
    'title': 'Рекорд 00-х',
    'url': 'https://radiorecord.hostingradio.ru/200096.aacp',
  },
  {
    'id': 520,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/mix_image600_white_fill.png',
    'title': 'Megamix',
    'url': 'https://radiorecord.hostingradio.ru/mix96.aacp',
  },
  {
    'id': 533,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/tm_image600_white_fill.png',
    'title': 'Trancemission',
    'url': 'https://radiorecord.hostingradio.ru/tm96.aacp',
  },
  {
    'id': 515,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/chillhouse_image600_white_fill.png',
    'title': 'Chill House',
    'url': 'https://radiorecord.hostingradio.ru/chillhouse96.aacp',
  },
  {
    'id': 501,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/bighits_image600_white_fill.png',
    'title': 'Big Hits',
    'url': 'https://radiorecord.hostingradio.ru/bighits96.aacp',
  },
  {
    'id': 493,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/gold_image600_white_fill.png',
    'title': 'Record Gold',
    'url': 'https://radiorecord.hostingradio.ru/gold96.aacp',
  },
  {
    'id': 43337,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/summerlounge_image600_white_fill.png',
    'title': 'Summer Lounge',
    'url': 'https://radiorecord.hostingradio.ru/summerlounge96.aacp',
  },
  {
    'id': 42725,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/summer-dance_image600_white_fill.png',
    'title': 'Summer Dance',
    'url': 'https://radiorecord.hostingradio.ru/summerparty96.aacp',
  },
  {
    'id': 548,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/rmx_image600_white_fill.png',
    'title': 'Remix',
    'url': 'https://radiorecord.hostingradio.ru/rmx96.aacp',
  },
  {
    'id': 43455,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/hype_image600_white_fill.png',
    'title': 'На Хайпе',
    'url': 'https://radiorecord.hostingradio.ru/hype96.aacp',
  },
  {
    'id': 524,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/russiangold_image600_white_fill.png',
    'title': 'Russian Gold',
    'url': 'https://radiorecord.hostingradio.ru/russiangold96.aacp',
  },
  {
    'id': 541,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/jackin_image600_white_fill.png',
    'title': 'Bass House',
    'url': 'https://radiorecord.hostingradio.ru/jackin96.aacp',
  },
  {
    'id': 43451,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/2010_image600_white_fill.png',
    'title': '10\'s Dance',
    'url': 'https://radiorecord.hostingradio.ru/201096.aacp',
  },
  {
    'id': 538,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/vip_image600_white_fill.png',
    'title': 'VIP House',
    'url': 'https://radiorecord.hostingradio.ru/vip96.aacp',
  },
  {
    'id': 510,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/trancehits_image600_white_fill.png',
    'title': 'Trance Classics',
    'url': 'https://radiorecord.hostingradio.ru/trancehits96.aacp',
  },
  {
    'id': 494,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/ibiza_image600_white_fill.png',
    'title': 'Innocence',
    'url': 'https://radiorecord.hostingradio.ru/ibiza96.aacp',
  },
  {
    'id': 500,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/househits_image600_white_fill.png',
    'title': 'House Hits',
    'url': 'https://radiorecord.hostingradio.ru/househits96.aacp',
  },
  {
    'id': 529,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/club_image600_white_fill.png',
    'title': 'EDM',
    'url': 'https://radiorecord.hostingradio.ru/club96.aacp',
  },
  {
    'id': 535,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/mini_image600_white_fill.png',
    'title': 'Minimal/Tech',
    'url': 'https://radiorecord.hostingradio.ru/mini96.aacp',
  },
  {
    'id': 43172,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/top-100-edm_image600_white_fill.png',
    'title': 'TOP 100 EDM',
    'url': 'https://radiorecord.hostingradio.ru/top100edm96.aacp',
  },
  {
    'id': 530,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/trop_image600_white_fill.png',
    'title': 'Tropical',
    'url': 'https://radiorecord.hostingradio.ru/trop96.aacp',
  },
  {
    'id': 43174,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/phonk_image600_white_fill.png',
    'title': 'Phonk',
    'url': 'https://radiorecord.hostingradio.ru/phonk96.aacp',
  },
  {
    'id': 43339,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/workout_image600_white_fill.png',
    'title': 'Workout',
    'url': 'https://radiorecord.hostingradio.ru/workout32.aacp',
  },
  {
    'id': 505,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/houseclss_image600_white_fill.png',
    'title': 'House Classics',
    'url': 'https://radiorecord.hostingradio.ru/houseclss96.aacp',
  },
  {
    'id': 523,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/drumhits_image600_white_fill.png',
    'title': 'D\'n\'B Classics',
    'url': 'https://radiorecord.hostingradio.ru/drumhits96.aacp',
  },
  {
    'id': 506,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/edmhits_image600_white_fill.png',
    'title': 'EDM Classics',
    'url': 'https://radiorecord.hostingradio.ru/edmhits96.aacp',
  },
  {
    'id': 42532,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/lofi_image600_white_fill.png',
    'title': 'Lo-Fi',
    'url': 'https://radiorecord.hostingradio.ru/lofi96.aacp',
  },
  {
    'id': 532,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/fut_image600_white_fill.png',
    'title': 'Future House',
    'url': 'https://radiorecord.hostingradio.ru/fut96.aacp',
  },
  {
    'id': 42715,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/organic_image600_white_fill.png',
    'title': 'Organic',
    'url': 'https://radiorecord.hostingradio.ru/organic96.aacp',
  },
  {
    'id': 552,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/trap_image600_white_fill.png',
    'title': 'Trap',
    'url': 'https://radiorecord.hostingradio.ru/trap96.aacp',
  },
  {
    'id': 43454,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/futurerave_image600_white_fill.png',
    'title': 'Future Rave',
    'url': 'https://radiorecord.hostingradio.ru/futurerave96.aacp',
  },
  {
    'id': 42509,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/techouse_image600_white_fill.png',
    'title': 'Tech House',
    'url': 'https://radiorecord.hostingradio.ru/techouse96.aacp',
  },
  {
    'id': 512,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/rapclassics_image600_white_fill.png',
    'title': 'Rap Classics',
    'url': 'https://radiorecord.hostingradio.ru/rapclassics96.aacp',
  },
  {
    'id': 498,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/progr_image600_white_fill.png',
    'title': 'Progressive',
    'url': 'https://radiorecord.hostingradio.ru/progr96.aacp',
  },
  {
    'id': 544,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/brks_image600_white_fill.png',
    'title': 'Breaks',
    'url': 'https://radiorecord.hostingradio.ru/brks96.aacp',
  },
  {
    'id': 542,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/trancehouse_image600_white_fill.png',
    'title': 'Trancehouse',
    'url': 'https://radiorecord.hostingradio.ru/trancehouse96.aacp',
  },
  {
    'id': 511,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/rap_image600_white_fill.png',
    'title': 'Rap Hits',
    'url': 'https://radiorecord.hostingradio.ru/rap96.aacp',
  },
  {
    'id': 531,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/goa_image600_white_fill.png',
    'title': 'GOA/PSY',
    'url': 'https://radiorecord.hostingradio.ru/goa96.aacp',
  },
  {
    'id': 502,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/dream_image600_white_fill.png',
    'title': 'Dream Dance',
    'url': 'https://radiorecord.hostingradio.ru/dream96.aacp',
  },
  {
    'id': 558,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/yo_image600_white_fill.png',
    'title': 'Black Rap',
    'url': 'https://radiorecord.hostingradio.ru/yo96.aacp',
  },
  {
    'id': 42602,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/dream-pop_image600_white_fill.png',
    'title': 'Dream Pop',
    'url': 'https://radiorecord.hostingradio.ru/dreampop96.aacp',
  },
  {
    'id': 496,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/elect_image600_white_fill.png',
    'title': 'Electro',
    'url': 'https://radiorecord.hostingradio.ru/elect96.aacp',
  },
  {
    'id': 504,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/uplift_image600_white_fill.png',
    'title': 'Uplifting',
    'url': 'https://radiorecord.hostingradio.ru/uplift96.aacp',
  },
  {
    'id': 549,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/fbass_image600_white_fill.png',
    'title': 'Future Bass',
    'url': 'https://radiorecord.hostingradio.ru/fbass96.aacp',
  },
  {
    'id': 42650,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/ambient_image600_white_fill.png',
    'title': 'Ambient',
    'url': 'https://radiorecord.hostingradio.ru/ambient96.aacp',
  },
  {
    'id': 507,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/neurofunk_image600_white_fill.png',
    'title': 'Neurofunk',
    'url': 'https://radiorecord.hostingradio.ru/neurofunk96.aacp',
  },
  {
    'id': 546,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/dc_image600_white_fill.png',
    'title': 'Dancecore',
    'url': 'https://radiorecord.hostingradio.ru/dc96.aacp',
  },
  {
    'id': 522,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/liquidfunk_image600_white_fill.png',
    'title': 'Liquid Funk',
    'url': 'https://radiorecord.hostingradio.ru/liquidfunk96.aacp',
  },
  {
    'id': 43338,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/reggae_image600_white_fill.png',
    'title': 'Reggae',
    'url': 'https://radiorecord.hostingradio.ru/reggae32.aacp',
  },
  {
    'id': 43452,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/latina_image600_white_fill.png',
    'title': 'Latina Dance',
    'url': 'https://radiorecord.hostingradio.ru/latina96.aacp',
  },
  {
    'id': 525,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/eurodance_image600_white_fill.png',
    'title': 'Eurodance',
    'url': 'https://radiorecord.hostingradio.ru/eurodance96.aacp',
  },
  {
    'id': 545,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/dub_image600_white_fill.png',
    'title': 'Dubstep',
    'url': 'https://radiorecord.hostingradio.ru/dub96.aacp',
  },
  {
    'id': 526,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/technopop_image600_white_fill.png',
    'title': 'Technopop',
    'url': 'https://radiorecord.hostingradio.ru/technopop96.aacp',
  },
  {
    'id': 547,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/techno_image600_white_fill.png',
    'title': 'Techno',
    'url': 'https://radiorecord.hostingradio.ru/techno96.aacp',
  },
  {
    'id': 527,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/discofunk_image600_white_fill.png',
    'title': 'Disco/Funk',
    'url': 'https://radiorecord.hostingradio.ru/discofunk96.aacp',
  },
  {
    'id': 43171,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/uk-garage_image600_white_fill.png',
    'title': 'UK Garage',
    'url': 'https://radiorecord.hostingradio.ru/ukgarage96.aacp',
  },
  {
    'id': 550,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/teo_image600_white_fill.png',
    'title': 'Hardstyle',
    'url': 'https://radiorecord.hostingradio.ru/teo96.aacp',
  },
  {
    'id': 508,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/tecktonik_image600_white_fill.png',
    'title': 'Tecktonik',
    'url': 'https://radiorecord.hostingradio.ru/tecktonik96.aacp',
  },
  {
    'id': 43173,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/live-dj-sets_image600_white_fill.png',
    'title': 'Live DJ-sets',
    'url': 'https://radiorecord.hostingradio.ru/livedjsets96.aacp',
  },
  {
    'id': 497,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/mt_image600_white_fill.png',
    'title': 'Midtempo',
    'url': 'https://radiorecord.hostingradio.ru/mt96.aacp',
  },
  {
    'id': 499,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/synth_image600_white_fill.png',
    'title': 'Synthwave',
    'url': 'https://radiorecord.hostingradio.ru/synth96.aacp',
  },
  {
    'id': 553,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/pump_image600_white_fill.png',
    'title': 'Old School',
    'url': 'https://radiorecord.hostingradio.ru/pump96.aacp',
  },
  {
    'id': 551,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/hbass_image600_white_fill.png',
    'title': 'Hard Bass',
    'url': 'https://radiorecord.hostingradio.ru/hbass96.aacp',
  },
  {
    'id': 503,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/darkside_image600_white_fill.png',
    'title': 'Darkside',
    'url': 'https://radiorecord.hostingradio.ru/darkside96.aacp',
  },
  {
    'id': 543,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/hypno_image600_white_fill.png',
    'title': 'Hypnotic',
    'url': 'https://radiorecord.hostingradio.ru/hypno96.aacp',
  },
  {
    'id': 540,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/mmbt_image600_white_fill.png',
    'title': 'Moombahton',
    'url': 'https://radiorecord.hostingradio.ru/mmbt96.aacp',
  },
  {
    'id': 509,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/2step_image600_white_fill.png',
    'title': '2-step',
    'url': 'https://radiorecord.hostingradio.ru/2step96.aacp',
  },
  {
    'id': 518,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/groovetribal_image600_white_fill.png',
    'title': 'Groove/Tribal',
    'url': 'https://radiorecord.hostingradio.ru/groovetribal96.aacp',
  },
  {
    'id': 559,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/rave_image600_white_fill.png',
    'title': 'Rave FM',
    'url': 'https://radiorecord.hostingradio.ru/rave96.aacp',
  },
  {
    'id': 521,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/jungle_image600_white_fill.png',
    'title': 'Jungle',
    'url': 'https://radiorecord.hostingradio.ru/jungle96.aacp',
  },
  {
    'id': 517,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/complextro_image600_white_fill.png',
    'title': 'Complextro',
    'url': 'https://radiorecord.hostingradio.ru/complextro96.aacp',
  },
  {
    'id': 556,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/gop_image600_white_fill.png',
    'title': 'Гоп FM',
    'url': 'https://radiorecord.hostingradio.ru/gop96.aacp',
  },
  {
    'id': 554,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/rock_image600_white_fill.png',
    'title': 'Rock',
    'url': 'https://radiorecord.hostingradio.ru/rock96.aacp',
  },
  {
    'id': 513,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/cadillac_image600_white_fill.png',
    'title': '60\'s Dance',
    'url': 'https://radiorecord.hostingradio.ru/cadillac96.aacp',
  },
  {
    'id': 516,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/1970_image600_white_fill.png',
    'title': '70\'s Dance',
    'url': 'https://radiorecord.hostingradio.ru/197096.aacp',
  },
  {
    'id': 514,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/1980_image600_white_fill.png',
    'title': 'Record 80-х',
    'url': 'https://radiorecord.hostingradio.ru/198096.aacp',
  },
  {
    'id': 14954,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/rv19_image600_white_fill.png',
    'title': 'Руки Вверх!',
    'url': 'https://radiorecord.hostingradio.ru/rv96.aacp',
  },
  {
    'id': 14718,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/deti_image600_white_fill.png',
    'title': 'Веснушка FM',
    'url': 'https://radiorecord.hostingradio.ru/deti96.aacp',
  },
  {
    'id': 555,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/mdl_image600_white_fill.png',
    'title': 'Медляк FM',
    'url': 'https://radiorecord.hostingradio.ru/mdl96.aacp',
  },
  {
    'id': 561,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/naft_image600_white_fill.png',
    'title': 'Нафталин FM',
    'url': 'https://radiorecord.hostingradio.ru/naft96.aacp',
  },
  {
    'id': 560,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/gast_image600_white_fill.png',
    'title': 'Гастарбайтер FM',
    'url': 'https://radiorecord.hostingradio.ru/gast96.aacp',
  },
  {
    'id': 557,
    'preview': 'https://www.radiorecord.ru/upload/stations_images/symph_image600_white_fill.png',
    'title': 'Симфония FM',
    'url': 'https://radiorecord.hostingradio.ru/symph96.aacp',
  },
];
